server:
  port: 5000
---
environment: production
spring:
  config:
    activate:
      on-profile: prod
name: prod-YAML
server:
  port: 5000
myCustomVarTree:
  welcomeMsg: "Hello from prod"
---
environment: testing
spring:
  config:
    activate:
      on-profile: test
name: test-YAML
server:
  port: 4000
myCustomVarTree:
  welcomeMsg: "Hello from test"